# Generated by Django 4.0.4 on 2022-04-22 03:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('talker', models.CharField(choices=[('Takumi', '男性'), ('Mizuki', '女性')], max_length=10)),
                ('remark', models.TextField(max_length=400)),
                ('audio', models.FileField(blank=True, null=True, upload_to='polly_speech')),
            ],
        ),
    ]
